<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.adacore.gnatpolyglot</groupId>
    <artifactId>gnatpolyglot</artifactId>
    <version>0.1.0</version>
  </parent>

  <artifactId>ada2proxy</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.adacore.gnatpolyglot</groupId>
      <artifactId>proxy</artifactId>
      <version>${project.parent.version}</version>
    </dependency>

    <dependency>
      <groupId>com.adacore</groupId>
      <artifactId>libadalang</artifactId>
      <version>${config.libadalang.version}</version>
    </dependency>

    <dependency>
      <groupId>gg.jte</groupId>
      <artifactId>jte-runtime</artifactId>
      <version>${config.jte.version}</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>${project.build.directory}/generated-resources</directory>
      </resource>
    </resources>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.2</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <finalName>ada2proxy</finalName>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Skip the Spotless check because everything is handled by the parent-->
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.40.0</version>
        <configuration>
          <skip>false</skip>
        </configuration>
      </plugin>

      <!-- Configure the template engine plugin -->
      <plugin>
        <groupId>gg.jte</groupId>
        <artifactId>jte-maven-plugin</artifactId>
        <version>${config.jte.version}</version>
        <configuration>
          <extensions>
            <extension>
              <className>gg.jte.nativeimage.NativeResourcesExtension</className>
            </extension>
          </extensions>
          <sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
          <targetResourceDirectory>${project.build.directory}/classes/</targetResourceDirectory>
          <contentType>Plain</contentType>
          <packageName>gg.jte.generate.precompiled.ada2proxy</packageName>
        </configuration>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>gg.jte</groupId>
            <artifactId>jte-native-resources</artifactId>
            <version>${config.jte.version}</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>info.picocli</groupId>
              <artifactId>picocli-codegen</artifactId>
              <version>4.7.7</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
