//
//  Copyright (C) 2025-2026, AdaCore
//  SPDX-License-Identifier: GPL-3.0-or-later
//

package com.adacore.polyglot.cli;

import com.adacore.polyglot.PolyglotUtils;
import com.adacore.polyglot.PolyglotUtils.VerboseLevel;
import com.adacore.polyglot.ada2proxy.Ada2Proxy;
import com.adacore.polyglot.proxy.PolyglotSetup;
import com.adacore.polyglot.proxy.ProxyValidator;
import com.adacore.polyglot.proxy2cpp.Proxy2Cpp;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.ScopeType;

@Command(
        name = "polyglot",
        subcommands = {ProxyValidator.class, Ada2Proxy.class, Proxy2Cpp.class, PolyglotSetup.class},
        // Version information are substituted by anod for production builds
        version = {
            "Polyglot <POLYGLOT_VERSION>",
            "Copyright (C) 2025-2026, AdaCore.",
            "Tools are licensed under GPL-3.0-or-later.",
            "Runtime libraries are licensed under Apache-2.0."
        },
        description = {
            "Polyglot - Multi-language interface generator.",
            "See documentation for more information."
        })
public class PolyglotMain {
    @Option(
            names = {"-h", "--help"},
            usageHelp = true,
            description = "display usage and exit")
    boolean helpRequested;

    @Option(
            names = {"--version"},
            versionHelp = true,
            description = "display version and exit")
    boolean versionRequested;

    @Option(
            names = {"-q"},
            description = "be quiet",
            scope = ScopeType.INHERIT,
            order = 1)
    public void setQuiet(boolean quiet) {
        if (quiet) PolyglotUtils.setVerbose(VerboseLevel.QUIET);
    }

    @Option(
            names = {
                "-v",
            },
            description = "verbose output",
            scope = ScopeType.INHERIT,
            order = 2)
    public void setVerbose(boolean verbose) {
        if (verbose) PolyglotUtils.setVerbose(VerboseLevel.VERBOSE);
    }

    @Option(
            names = {"--header-file"},
            description =
                    "prepend the content of the given file to all sources generated by Polyglot.",
            scope = ScopeType.INHERIT)
    public void setHeaderFile(String headerFile) throws java.io.IOException {
        PolyglotUtils.setHeaderFile(headerFile);
    }

    public static void main(String... args) {
        System.exit(new CommandLine(new PolyglotMain()).execute(args));
    }
}
