"""
Check that passing a parent directory using a relative path works as
as expected in the various polyglot's subcommands.
"""

from utils import run_polyglot, list_generated_sources

import os
import os.path

os.chdir("src")

proxy_dir = os.path.join("..", "proxy")  # important: involve a ".."
proxy_file = os.path.join(proxy_dir, "proxy.json")

# Check scanners behavior

run_polyglot(
    "ada2proxy",
    ["-P", "test.gpr", "-o", proxy_dir],
)
assert os.path.isdir(proxy_dir)

# Check printers behavior.
# Note that for simplicity, we exploit the proxy files generated by the
# previous subcommands, but ideally the following subcommands wouldn't depend
# on the previous ones being successful.

for lang in ["cpp", "java", "rust"]:
    subcommand = f"proxy2{lang}"
    out_dir = os.path.join("..", f"out_{lang}")  # important: involve a ".."
    run_polyglot(
        subcommand,
        [proxy_file, "-o", out_dir]
    )
    assert os.path.isdir(out_dir)
