//
//  Copyright (C) 2025-2026, AdaCore
//  SPDX-License-Identifier: GPL-3.0-or-later
//

package com.adacore.gnatpolyglot.cli;

import com.adacore.gnatpolyglot.GNATpolyglotUtils;
import com.adacore.gnatpolyglot.GNATpolyglotUtils.VerboseLevel;
import com.adacore.gnatpolyglot.ada2proxy.Ada2Proxy;
import com.adacore.gnatpolyglot.proxy.GNATpolyglotSetup;
import com.adacore.gnatpolyglot.proxy.ProxyValidator;
import com.adacore.gnatpolyglot.proxy2cpp.Proxy2Cpp;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.ScopeType;

@Command(
        name = "gnatpolyglot",
        subcommands = {
            ProxyValidator.class,
            Ada2Proxy.class,
            Proxy2Cpp.class,
            GNATpolyglotSetup.class
        },
        // Version information are substituted by anod for production builds
        version = {
            "GNATpolyglot <POLYGLOT_VERSION>",
            "Copyright (C) 2025-2026, AdaCore.",
            "Tools are licensed under GPL-3.0-or-later.",
            "Runtime libraries are licensed under Apache-2.0."
        },
        description = {
            "GNATpolyglot - Multi-language interface generator.",
            "See documentation for more information."
        })
public class GNATpolyglotMain {
    @Option(
            names = {"-h", "--help"},
            usageHelp = true,
            description = "display usage and exit")
    boolean helpRequested;

    @Option(
            names = {"--version"},
            versionHelp = true,
            description = "display version and exit")
    boolean versionRequested;

    @Option(
            names = {"-q"},
            description = "be quiet",
            scope = ScopeType.INHERIT,
            order = 1)
    public void setQuiet(boolean quiet) {
        if (quiet) GNATpolyglotUtils.setVerbose(VerboseLevel.QUIET);
    }

    @Option(
            names = {
                "-v",
            },
            description = "verbose output",
            scope = ScopeType.INHERIT,
            order = 2)
    public void setVerbose(boolean verbose) {
        if (verbose) GNATpolyglotUtils.setVerbose(VerboseLevel.VERBOSE);
    }

    @Option(
            names = {"--header-file"},
            description =
                    "prepend the content of the given file to all sources generated by"
                            + " GNATpolyglot.",
            scope = ScopeType.INHERIT)
    public void setHeaderFile(String headerFile) throws java.io.IOException {
        GNATpolyglotUtils.setHeaderFile(headerFile);
    }

    public static void main(String... args) {
        System.exit(new CommandLine(new GNATpolyglotMain()).execute(args));
    }
}
