<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.adacore.polyglot</groupId>
  <artifactId>polyglot</artifactId>
  <packaging>pom</packaging>
  <version>0.1.0</version>
  <modules>
    <module>cli</module>
    <module>proxy</module>
    <module>ada2proxy</module>
    <module>proxy2cpp</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <!--
      Maven Surefire does not provide a CLI argument to choose the reportsDirectory.
      To configure this, change the value of this property (-Dmaven.surefire.reportsDirectory=...)
    -->
    <maven.surefire.reportsDirectory>
      ${project.build.directory}/surefire-reports
    </maven.surefire.reportsDirectory>

    <jte.version>3.1.16</jte.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>info.picocli</groupId>
      <artifactId>picocli</artifactId>
      <version>4.7.7</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <reportsDirectory>${maven.surefire.reportsDirectory}</reportsDirectory>
        </configuration>
      </plugin>

      <!-- Configure the spotless Java formatter -->
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.40.0</version>

        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>validate</phase>
          </execution>
        </executions>

        <configuration>
          <java>
            <includes>
              <include>proxy/src/*/java/**/*.java</include>
              <include>ada2proxy/src/*/java/**/*.java</include>
              <include>proxy2cpp/src/*/java/**/*.java</include>
            </includes>

            <googleJavaFormat>
              <version>1.17.0</version>
              <style>AOSP</style>
              <reflowLongStrings>true</reflowLongStrings>
              <formatJavadoc>true</formatJavadoc>
            </googleJavaFormat>

            <importOrder>
              <wildcardsLast>true</wildcardsLast>
              <semanticSort>true</semanticSort>
            </importOrder>
            <formatAnnotations/>
            <removeUnusedImports/>
          </java>
          <lineEndings>UNIX</lineEndings>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>

